tarea 1/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html]
# get 'home/index'
root 'home#index'
get 'home', to: 'home#index'
get 'search', to: 'home#search'

post 'home/', to: 'home#query'
# get 'search_title', to: 'home#search'
# get 'search_people', to: 'home#search'

end

tarea 1/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

tarea 1/app/models/home.rb
class Home < ApplicationRecord
  include HTTParty
  @@format = 'json'

  base_uri = "https://swapi.co/api/"
  format :json

  # def swapi
  #   # self.class.get('/films?format=' + @@json)['results']['0']
  #   # get("", query = { query : term})["results"]
  # end
  
end

tarea 1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

tarea 1/app/controllers/home_controller.rb
class HomeController < ApplicationController
  include HTTParty
  @@format = '&format=json'

  def index
    @calls = HTTParty.get('https://swapi.co/api/films?format=json', :headers =>{'Content-Type' => 'application/json'})['results']
    # @calls = Home.swapi
  end

  def query
    @type = params[:type]
    @info = '?search=' + params[:info].to_s
    @url = [@type, @info].join('/')
    @url = [@url, @@format].join('')
    @calls = HTTParty.get('https://swapi.co/api/' + @url, :headers =>{'Content-Type' => 'application/json'})['results']
  end

  def search
    @type = params[:type] + '/'
    @url = '?search=' + params[:info].to_s
    @url = [@url, @@format].join('')

    @people = HTTParty.get('https://swapi.co/api/people' + @url, :headers =>{'Content-Type' => 'application/json'})['results']
    @starships = HTTParty.get('https://swapi.co/api/starships' + @url, :headers =>{'Content-Type' => 'application/json'})['results']
    @films = HTTParty.get('https://swapi.co/api/films' + @url, :headers =>{'Content-Type' => 'application/json'})['results']
    @planets = HTTParty.get('https://swapi.co/api/planets' + @url, :headers =>{'Content-Type' => 'application/json'})['results']

    @response = HTTParty.get('https://swapi.co/api/' + @type + @url, :headers =>{'Content-Type' => 'application/json'})['results']

  end

end

tarea 1/app/helpers/application_helper.rb
module ApplicationHelper
end

tarea 1/app/helpers/home_helper.rb
module HomeHelper
end

tarea 1/app/views/home/index.html.erb
<section id="about">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 mx-auto">
        <h2>Peliculas de Starwars</h2>
        <p class="lead">Todas las peliculas con su info.</p>

          <table border="1">
            <tr>
              <th>Nombre</th>
              <th>Año de lanzamiento</th>
              <th>Director</th>
              <th>Productores</th>
              <th>Episodio en la saga</th>
            </tr>

            <% @calls.each do |call| %>

              <tr>
                <td style="text-align:left">
                  <a href='search?type=films'>
                    <%= call['title'] %>
                  </a>
                </td>

                <td style="text-align:center"><%= call['release_date'] %></td>

                <td style="text-align:center">
                  <a href= 'search?type=people&info=<%= call['director'].rpartition(" ").first.downcase %>' >
                    <%= call['director'] %>
                  </a>
                </td>


                <td style="text-align:center">
                <% call['producer'].split(',').each do |name| %>
                    <a href='search?type=people&info=<%= name.rpartition(" ").first.downcase %>' >
                      <%= name %>
                    </a>
                <% end %>
                </td>

                <td style="text-align:center"><%= call['episode_id'] %></td>
              </tr>

            <% end %>
          </table>

      </div>
    </div>
  </div>
</section>

tarea 1/app/views/home/query.html.erb
<html>

  <h3>API response <br>
  </h3>
  <body>




    <table border="0">
    <caption>RESULTADOS</caption>

      <% @calls.each do |call| %>
      <tr>
        <td style="text-align:left">

          <a href='search?info=<%= call['name'] %>&type=people'>
            <%= call['name'] %>
          </a>
        </td>
        <td>
          <a href='search?info=<%= call['title'] %>&type=films'>
            <%= call['title'] %>
          </a>
        </td>
      </tr>
      <% end %>
    </table>

    <br>
    <br>
    <div class='col-md-4 text-center'>
    <%= button_to "Volver al inicio", root_url, :method => :get%>
    </div>
    <br>
    <br>
  </body>
</html>

tarea 1/app/views/home/search.html.erb
<html>

  <h2>
    API response<br>
    Resultados <br>
  </h2>
  <body>

    <br><h3>Personajes</h3><br>


    <% @people.each do |resultado| %>
      <table border="1">
        <% resultado.each do |key, val|%>
          <tr>
            <td><%= key.to_s %> </td>
            <td><%= val %></td>
          </tr>
        <% end %>
      </table>
      <br>
    <% end %>


    <br><br><h3>Peliculas</h3><br>

    <% @films.each do |resultado| %>
      <table border="1">
        <% resultado.each do |key, val|%>
          <tr>
            <td><%= key.to_s %> </td>
            <td><%= val %></td>
          </tr>
        <% end %>
      </table>
      <br>
    <% end %>

    <br><br><h3>Naves</h3><br>

    <% @starships.each do |resultado| %>
      <table border="1">
        <% resultado.each do |key, val|%>
          <tr>
            <td><%= key.to_s %> </td>
            <td><%= val %></td>
          </tr>
        <% end %>
      </table>
      <br>
    <% end %>

    <br><br><h3>Planetas</h3><br>

    <% @planets.each do |resultado| %>
      <table border="1">
        <% resultado.each do |key, val|%>
          <tr>
            <td><%= key.to_s %> </td>
            <td><%= val %></td>
          </tr>
        <% end %>
      </table>
      <br>
    <% end %>



    <br>
    <br>
    <div class='col-md-4 text-center'>
    <%= button_to "Volver al inicio", root_url, :method => :get%>
    </div>
    <br>
    <br>
  </body>
</html>

tarea 1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <style>
       table, td, th {
          border: 1px solid black;
          /* width: 300px; */
       }
    </style>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Tarea01</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/scrolling-nav.css" rel="stylesheet">

  </head>

  <body id="page-top">

    <!-- Navigation -->
    <header class="bg-primary text-white">
      <div class="container text-center">
        <h1>Tarea 01 - Taller de Integracion - API SWAPI</h1>
        <br>
          <%= form_tag home_path do %>
          <div class="field">
            <%= text_field_tag :info %>
            <%= select_tag(:type,
            options_for_select([
                                ['Pelicula', 'films'],
                                ['Persona', 'people'],
                                ['Nave', 'starships'],
                                ['Planeta', 'planets']
                                ]))%>
            <%= submit_tag "Buscar", class: "btn"%>
          </div>
          <% end %>
        <br>
      </div>
    </header>

    <%= yield %>

  </body>
</html>